-- Fix: Update currency order creation functions to follow proper authentication pattern
-- Following rule: Frontend calls get_current_profile_id(), Backend receives profiles.id as parameter

-- =====================================================
-- SAFE DROPS - Handle all possible function versions
-- =====================================================

-- Drop ALL versions of create_currency_purchase_order using CASCADE
-- This will drop the function and all dependent objects safely
DROP FUNCTION IF EXISTS create_currency_purchase_order() CASCADE;

-- Drop ALL versions of create_currency_purchase_order_draft using CASCADE
DROP FUNCTION IF EXISTS create_currency_purchase_order_draft() CASCADE;

-- =====================================================
-- RECREATE FUNCTIONS WITH PROPER AUTHENTICATION
-- =====================================================

-- Recreate create_currency_purchase_order with proper authentication pattern
CREATE OR REPLACE FUNCTION create_currency_purchase_order(
    p_currency_attribute_id UUID,
    p_quantity NUMERIC,
    p_cost_amount NUMERIC,
    p_cost_currency_code TEXT,
    p_game_code TEXT,
    p_server_attribute_code TEXT,
    p_channel_id UUID,
    p_supplier_name TEXT,
    p_supplier_contact TEXT,
    p_delivery_info TEXT,
    p_notes TEXT,
    p_priority_level INTEGER,
    p_user_id UUID  -- Required parameter: profiles.id from frontend
)
RETURNS TABLE (
    success BOOLEAN,
    order_id UUID,
    order_number TEXT,
    message TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_order_id UUID;
    v_order_number TEXT;
    v_currency_code TEXT;
    v_supplier_party_id UUID;
    v_currency_exists BOOLEAN;
BEGIN
    -- Validate user_id parameter (following authentication rule)
    IF p_user_id IS NULL THEN
        RETURN QUERY SELECT FALSE, NULL::UUID, NULL::TEXT, 'Authentication required: user_id cannot be null';
        RETURN;
    END IF;

    -- Validate currency exists
    SELECT EXISTS(SELECT 1 FROM attributes WHERE id = p_currency_attribute_id AND type LIKE '%CURRENCY%')
    INTO v_currency_exists;

    IF NOT v_currency_exists THEN
        RETURN QUERY SELECT FALSE, NULL::UUID, NULL::TEXT, 'Currency attribute not found or not a currency type';
        RETURN;
    END IF;

    -- Get currency code for reference
    SELECT code INTO v_currency_code
    FROM attributes
    WHERE id = p_currency_attribute_id;

    -- Validate channel exists
    IF NOT EXISTS(SELECT 1 FROM channels WHERE id = p_channel_id) THEN
        RETURN QUERY SELECT FALSE, NULL::UUID, NULL::TEXT, 'Channel not found';
        RETURN;
    END IF;

    -- Create or find supplier party with more flexible lookup
    IF p_supplier_name IS NOT NULL THEN
        -- Try to find existing supplier by name and type
        SELECT id INTO v_supplier_party_id
        FROM parties
        WHERE name = p_supplier_name
        AND type = 'supplier'
        LIMIT 1;

        -- Create new supplier if not found
        IF v_supplier_party_id IS NULL THEN
            BEGIN
                INSERT INTO parties (name, type, contact_info, notes, channel_id, game_code)
                VALUES (p_supplier_name, 'supplier',
                        jsonb_build_object('contact', COALESCE(p_supplier_contact, '')),
                        'Auto-created for purchase order',
                        p_channel_id,
                        p_game_code)
                RETURNING id INTO v_supplier_party_id;
            EXCEPTION
                WHEN unique_violation THEN
                    -- If we get a unique violation, try to find the existing supplier again
                    SELECT id INTO v_supplier_party_id
                    FROM parties
                    WHERE name = p_supplier_name
                    AND type = 'supplier'
                    LIMIT 1;

                    -- If still not found, return error
                    IF v_supplier_party_id IS NULL THEN
                        RETURN QUERY SELECT FALSE, NULL::UUID, NULL::TEXT, 'Unable to create or find supplier: ' || p_supplier_name;
                        RETURN;
                    END IF;
            END;
        END IF;
    ELSE
        RETURN QUERY SELECT FALSE, NULL::UUID, NULL::TEXT, 'Supplier name is required';
        RETURN;
    END IF;

    -- Create the purchase order - order_number will be auto-generated by trigger
    INSERT INTO public.currency_orders (
        order_type,
        currency_attribute_id,
        quantity,
        cost_amount,
        cost_currency_code,
        game_code,
        server_attribute_code,
        channel_id,
        party_id,
        delivery_info,
        notes,
        status,
        priority_level,
        deadline_at,
        created_at,
        created_by  -- Use proper profiles.id from parameter
    ) VALUES (
        'PURCHASE',
        p_currency_attribute_id,
        p_quantity,
        p_cost_amount,
        p_cost_currency_code,
        p_game_code,
        p_server_attribute_code,
        p_channel_id,
        v_supplier_party_id,
        p_delivery_info,
        p_notes,
        'pending',
        p_priority_level,
        NOW() + INTERVAL '24 hours',
        NOW(),
        p_user_id  -- Proper authentication: use profiles.id from frontend
    )
    RETURNING public.currency_orders.id, public.currency_orders.order_number INTO v_order_id, v_order_number;

    -- Return success
    RETURN QUERY SELECT
        TRUE,
        v_order_id,
        v_order_number,
        'Purchase order created successfully';

EXCEPTION
    WHEN OTHERS THEN
        RETURN QUERY SELECT
            FALSE,
            NULL::UUID,
            NULL::TEXT,
            'Error creating purchase order: ' || SQLERRM;
END;
$$;

-- Grant execute permission to authenticated users
GRANT EXECUTE ON FUNCTION create_currency_purchase_order TO authenticated;

-- Recreate create_currency_purchase_order_draft with proper authentication pattern
CREATE OR REPLACE FUNCTION create_currency_purchase_order_draft(
    p_currency_attribute_id UUID,
    p_quantity NUMERIC,
    p_cost_amount NUMERIC,
    p_cost_currency_code TEXT,
    p_game_code TEXT,
    p_server_attribute_code TEXT,
    p_channel_id UUID,
    p_supplier_name TEXT,
    p_supplier_contact TEXT,
    p_delivery_info TEXT,
    p_notes TEXT,
    p_priority_level INTEGER,
    p_user_id UUID  -- Required parameter: profiles.id from frontend
)
RETURNS TABLE (
    success BOOLEAN,
    order_id UUID,
    order_number TEXT,
    message TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_order_id UUID;
    v_order_number TEXT;
    v_currency_code TEXT;
    v_supplier_party_id UUID;
    v_currency_exists BOOLEAN;
    v_channel_code TEXT;
    v_cost_amount_final NUMERIC;
    v_cost_currency_code_final TEXT;
    v_delivery_info_final TEXT;      -- Game tag only
    v_notes_final TEXT;              -- Combined: delivery_contact_info | user_notes
    v_priority_level INTEGER;        -- Added missing declaration
BEGIN
    -- Set priority level from parameter or default
    v_priority_level := p_priority_level;

    -- Validate user_id parameter (following authentication rule)
    IF p_user_id IS NULL THEN
        RETURN QUERY SELECT FALSE, NULL::UUID, NULL::TEXT, 'Authentication required: user_id cannot be null';
        RETURN;
    END IF;

    -- Validate currency exists
    SELECT EXISTS(SELECT 1 FROM attributes WHERE id = p_currency_attribute_id AND type LIKE '%CURRENCY%')
    INTO v_currency_exists;

    IF NOT v_currency_exists THEN
        RETURN QUERY SELECT FALSE, NULL::UUID, NULL::TEXT, 'Currency attribute not found or not a currency type';
        RETURN;
    END IF;

    -- Get currency code for reference
    SELECT code INTO v_currency_code
    FROM attributes
    WHERE id = p_currency_attribute_id;

    -- Validate channel exists and get channel code
    SELECT code INTO v_channel_code
    FROM channels
    WHERE id = p_channel_id;

    IF v_channel_code IS NULL THEN
        RETURN QUERY SELECT FALSE, NULL::UUID, NULL::TEXT, 'Channel not found';
        RETURN;
    END IF;

    -- Use provided cost amount and currency, or defaults
    v_cost_amount_final := COALESCE(p_cost_amount, 0);
    v_cost_currency_code_final := COALESCE(p_cost_currency_code, 'VND');

    -- For WeChat channel, default to CNY if no currency specified
    IF v_channel_code = 'WeChat' AND v_cost_currency_code_final = 'VND' AND p_cost_currency_code IS NULL THEN
        v_cost_currency_code_final := 'CNY';
    END IF;

    -- Generate order number for purchase orders (using PO prefix instead of SO)
    v_order_number := 'PO' || TO_CHAR(NOW(), 'YYYYMMDD') || LPAD(EXTRACT(MICROSECONDS FROM NOW())::TEXT, 6, '0');

    -- UPDATED LOGIC: delivery_info contains game tag only
    v_delivery_info_final := COALESCE(p_delivery_info, '');

    -- UPDATED LOGIC: Build combined notes (delivery_contact_info | user_notes)
    v_notes_final := COALESCE(p_notes, '');

    -- Create or find supplier party with enhanced contact_info JSON
    IF p_supplier_name IS NOT NULL THEN
        SELECT id INTO v_supplier_party_id
        FROM parties
        WHERE name = p_supplier_name
        AND type = 'supplier'
        LIMIT 1;

        -- Create new supplier if not found
        IF v_supplier_party_id IS NULL THEN
            BEGIN
                INSERT INTO parties (name, type, contact_info, notes, channel_id, game_code)
                VALUES (p_supplier_name, 'supplier',
                        jsonb_build_object(
                            'contact', COALESCE(p_supplier_contact, ''),
                            'gameTag', v_delivery_info_final,      -- Game tag from delivery_info
                            'deliveryInfo', ''                    -- Suppliers don't need delivery info
                        ),
                        'Auto-created for purchase order draft',
                        p_channel_id,
                        p_game_code)
                RETURNING id INTO v_supplier_party_id;
            EXCEPTION
                WHEN unique_violation THEN
                    SELECT id INTO v_supplier_party_id
                    FROM parties
                    WHERE name = p_supplier_name
                    AND type = 'supplier'
                    LIMIT 1;

                    IF v_supplier_party_id IS NULL THEN
                        RETURN QUERY SELECT FALSE, NULL::UUID, NULL::TEXT, 'Unable to create or find supplier: ' || p_supplier_name;
                        RETURN;
                    END IF;
            END;
        ELSE
            -- Update existing supplier party with new contact info if provided
            UPDATE parties
            SET
                contact_info = jsonb_build_object(
                    'contact', COALESCE(p_supplier_contact, (contact_info->>'contact')),
                    'gameTag', v_delivery_info_final,      -- Game tag from delivery_info
                    'deliveryInfo', ''                    -- Suppliers don't need delivery info
                ),
                updated_at = NOW()
            WHERE id = v_supplier_party_id;
        END IF;
    ELSE
        RETURN QUERY SELECT FALSE, NULL::UUID, NULL::TEXT, 'Supplier name is required';
        RETURN;
    END IF;

    -- FIXED: Purchase orders only track cost, sale/profit fields are NULL
    INSERT INTO public.currency_orders (
        order_number,
        order_type,
        currency_attribute_id,
        quantity,
        cost_amount,
        cost_currency_code,
        sale_amount,                    -- NULL for purchase orders
        sale_currency_code,              -- NULL for purchase orders
        profit_amount,                   -- NULL for purchase orders
        profit_currency_code,            -- NULL for purchase orders
        profit_margin_percentage,         -- NULL for purchase orders
        cost_to_sale_exchange_rate,       -- NULL for purchase orders
        exchange_rate_date,               -- NULL for purchase orders
        exchange_rate_source,             -- NULL for purchase orders
        game_code,
        server_attribute_code,
        channel_id,
        party_id,
        delivery_info,                   -- Game tag only
        notes,                            -- delivery_contact_info | user_notes
        status,
        priority_level,
        deadline_at,
        created_at,
        created_by,                      -- Use proper profiles.id from parameter
        proofs
    ) VALUES (
        v_order_number,                  -- Generated order number
        'PURCHASE',
        p_currency_attribute_id,
        p_quantity,
        v_cost_amount_final,
        v_cost_currency_code_final,
        NULL,        -- sale_amount = NULL for purchase orders
        NULL,        -- sale_currency_code = NULL for purchase orders
        NULL,        -- profit_amount = NULL for purchase orders
        NULL,        -- profit_currency_code = NULL for purchase orders
        NULL,        -- profit_margin_percentage = NULL for purchase orders
        NULL,        -- cost_to_sale_exchange_rate = NULL for purchase orders
        NULL,        -- exchange_rate_date = NULL for purchase orders
        NULL,        -- exchange_rate_source = NULL for purchase orders
        p_game_code,
        p_server_attribute_code,
        p_channel_id,
        v_supplier_party_id,
        v_delivery_info_final,            -- Game tag only
        v_notes_final,                     -- delivery_contact_info | user_notes
        'draft',
        v_priority_level,                -- Use declared variable
        NOW() + INTERVAL '24 hours',
        NOW(),
        p_user_id,                        -- Proper authentication: use profiles.id from frontend
        '{}'::jsonb
    ) RETURNING public.currency_orders.id, public.currency_orders.order_number INTO v_order_id, v_order_number;

    -- Return success - updated message to reflect the fix
    RETURN QUERY SELECT
        TRUE,
        v_order_id,
        v_order_number,
        format('Purchase order draft created successfully - Order: %s. Cost: %s %s. Sale/profit will be calculated when order is actually sold.',
               v_order_number, v_cost_amount_final, v_cost_currency_code_final);

EXCEPTION
    WHEN OTHERS THEN
        RETURN QUERY SELECT
            FALSE,
            NULL::UUID,
            NULL::TEXT,
            'Error creating purchase order draft: ' || SQLERRM;
END;
$$;

-- Grant execute permission to authenticated users
GRANT EXECUTE ON FUNCTION create_currency_purchase_order_draft TO authenticated;

-- =====================================================
-- VERIFICATION
-- =====================================================

-- Verify functions were created correctly
-- This query should return the two functions with their new signatures
DO $$
BEGIN
    RAISE NOTICE 'Migration completed: Functions updated with proper authentication pattern';
    RAISE NOTICE 'create_currency_purchase_order now requires p_user_id parameter';
    RAISE NOTICE 'create_currency_purchase_order_draft now requires p_user_id parameter';
    RAISE NOTICE 'Both functions follow the rule: Frontend calls get_current_profile_id(), Backend receives profiles.id as parameter';
END $$;